version: "3.1"
services:
  backend:
    build:
      context: ./
      dockerfile: ./Docker/backend_dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./
      dockerfile: ./Docker/frontend_dockerfile
    ports:
      - "80:80"
  redis:
    image: "redis"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
