version: "3.1"

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
  
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend-dockerfile-prod
    ports:
      - "8080:8080"
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
  
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend-dockerfile-prod
    ports:
      - "80:80"
    volumes:
      - ./certs/certbot/conf:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot
  
  redis:
    image: "redis"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
