version: "3.1"
services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend-dockerfile-prod
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs:/etc/ssl/certs
  
  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend-dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl/certs:/etc/ssl/certs
  
  redis:
    image: "redis"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
  
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
